version: '3'

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    depends_on:
      - wordpress
    volumes:
      - "/home/facolomb/data/www:/var/www/html"
    restart: always
    ports:
      - "443:443"
    env_file:
      - .env
    networks:
      - n_inception

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - "/home/facolomb/data/mysql:/var//lib/mysql"
    ports:
      - "3306:3306"
    restart: always
    env_file:
      - .env
    networks:
      - n_inception

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    volumes:
      - "/home/facolomb/data/www:/var/www/html"
    ports:
      - "9000:9000"
    restart: always
    env_file:
      - .env
    networks:
      - n_inception

networks:
  n_inception:
    driver: bridge